### ISSUE TITLE
Ahorn starts too slow

### ISSUE THREAD

**Issue by nahaijgnauh** [CelestialCartographers/Ahorn#20]
It took about half a minute to start it

**Comment by EricForgy** [comment]
As a Julia evangelist, I love this package ❤️ 

There is currently a ton of work going on in the Julia community to improve "Time to first plot" including precompilation tricks and static compilation that I think this package could benefit a lot from. I encourage you to join the Julia Slack. People would be thrilled to help out.

**Comment by ExpandingMan** [comment]
This seems like a project for which [PackageCompiler](https://github.com/JuliaLang/PackageCompiler.jl) is essential.  I haven't looked to much at what you guys did here, but I encourage you to try it.

Unfortunately because of the rather novel way the Julia compiler works, statically compiling is non-trivial, however there has been some good progress on this front.  It's not totally solved, so I'm not sure it will completely cut it for this use case, but PackageCompiler is far more usable now than it was a year ago.
