### ISSUE TITLE
Ahorn start up takes very long - causes keyboard issues on Windows 10

### ISSUE THREAD

**Issue by michelfaria** [CelestialCartographers/Ahorn#29]
Operating System: Windows 10
Version: 19041.508

The Ahorn startup takes 30-60 seconds and causes the keyboard to lag system-wide. Also, during the startup phase, keyboard inputs system-wide will lag 2-4 second between each other, which hinders the user's usage of other applications during that time.

**Comment by Cruor** [comment]
GTK on Windows in general causes keyboard lag. Nothing we can do about that sadly. Neither is there much we can do about startup time. It has already been reduced a fair bit, but it is mostly down to importing our dependencies now.

**Comment by michelfaria** [comment]
What is the cause for the long startup time, exactly?

**Comment by Cruor** [comment]
Packages that don't precompile properly (or functions/modules that are explicitly told not to precompile) and have to do "warmup". Just importing the GTK package takes around 10 seconds, which you can technically get around by making a system image of it. In that case it is instant, but it makes updating the program for users even more of a painful process.

Some of the time also goes to reading any external plugins that are in the mods folder, say custom decals so Ahorn can put them in the list. If you have larger mods (like the recent Spring Collab 2020) this takes a bit of time for crawling through the structure and picking out potential assets it might find useful. You can disable loading assets from zips entirely in the settings, but I don't honestly know how much it helps.

Thats at least what seems to be the worst parts of startup from what I have seen. Everything is also slower on Windows because of NTFS and small files being a thing.

**Comment by michelfaria** [comment]
> Just importing the GTK package takes around 10 seconds, which you can technically get around by making a system image of it. In that case it is instant, but it makes updating the program for users even more of a painful process.¨
How much more painful would updating the program be for users? Would the trade-off of a faster loading time not be worth it?

**Comment by Cruor** [comment]
It is not worth it at all, it requires deleting the system image and regenerating it on every update. Regenerating it takes a lot of time as well. The updating and installation process is already time consuming and full of errors, it's not worth doing it officially in my opinion. It also increases install size by another ~200MB. 

If you are interested in doing it on your own install you can always run Ahorn with `test/runahorn.jl` instead. That is the "developer" way to start the program. Here is a link for [Package Compiler](https://github.com/JuliaLang/PackageCompiler.jl), I don't exactly remember the instructions for using it off the top of my head, but it does the job. Just know that anything it compiles takes precedence over new code.
